Repository ureca-capstone4/idle-server, pull requests merged in 2024-10, with the labels that each got.

#2 [ID-9] PullRequestTemplate 설정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 [ID-24] JPA 모듈 개발
  src/main/java/com/ureca/idle/idlejpa/book/Book.java
  src/main/java/com/ureca/idle/idlejpa/booksdetail/BooksDetail.java
  src/main/java/com/ureca/idle/idlejpa/kid/Kid.java
  src/main/java/com/ureca/idle/idlejpa/kidspersonality/KidsPersonality.java
  src/main/java/com/ureca/idle/idlejpa/preferences/Hobulho.java
  src/main/java/com/ureca/idle/idlejpa/preferences/Preferences.java
Labels: enhancement

#16 [ID-26] AI API 추가
  .gitignore
  build.gradle
  gradlew
  src/main/java/com/ureca/idle/idleaiclient/AIService.java
  src/main/java/com/ureca/idle/idleaiclient/LGAIClient.java
  src/main/java/com/ureca/idle/idleaiclient/config/RestTemplateConfig.java
  src/main/java/com/ureca/idle/idleaiclient/dto/AddBookMbtiReq.java
  src/main/java/com/ureca/idle/idleaiclient/dto/AddBookMbtiResp.java
  src/main/resources/application.yml
  src/test/java/com/ureca/idle/idleaiclient/AiClientTest.java
Labels: enhancement

#19 [ID-27] 도서 컨텐츠 추가, 조회, 수정, 삭제 기능 추가
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/auth/SimpleJwtAuthService.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/BookManagingService.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/BookManagingUseCase.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/AddBookReq.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/AddBookResp.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/DeleteBookReq.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/GetBookDetailResp.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/UpdateBookReq.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/common/exception/book/BookException.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/common/exception/book/BookExceptionType.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/book/BookManager.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/mapper/BookDtoMapper.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/user/UserManager.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/book/BookPreferenceRepository.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/persistence/book/BookRepository.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentaion/web/auth/IdAndAuthority.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentaion/web/jwt/JwtDto.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/controller/auth/AuthController.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/controller/book/BookManagingController.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/controller/kid/KidManagingController.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/controller/metric/HealthController.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/auth/IdAndAuthority.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/auth/LoginUser.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/auth/LoginUserArgumentResolver.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/config/WebConfig.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/jwt/JwtDto.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/jwt/JwtException.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/jwt/JwtProperties.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/presentation/web/jwt/JwtProvider.java
  src/main/java/com/ureca/idle/idlejpa/book/Book.java
  src/main/java/com/ureca/idle/idlejpa/bookscharacteristic/BooksCharacteristic.java
Labels: enhancement

#29 [ID-43] 도서 컨텐츠 CRUD 추가 작업
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/AddBookReq.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/DeleteBookReq.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/GetBookDetailResp.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/GetBookProfileResp.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/business/book/dto/UpdateBookReq.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/book/BookManager.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/mapper/BookDtoMapper.java
  src/main/java/com/ureca/idle/idleapi/idleoriginapi/implementation/util/MBTIUtil.java
  src/main/java/com/ureca/idle/idlejpa/book/Book.java
  src/test/java/com/ureca/idle/idleapi/idleoriginapi/implementation/BookManagerTest.java
Labels: enhancement

#36 [ID-61] 자녀성향 히스토리 배치 기능 구현
  build.gradle
  src/main/java/com/ureca/idle/IdleApplication.java
  src/main/java/com/ureca/idle/batch/IdleBatch.java
  src/main/java/com/ureca/idle/batch/ScheduledTasks.java
  src/main/java/com/ureca/idle/batch/kidspersonalitybatch/KidsPersonalityBatchManager.java
  src/main/java/com/ureca/idle/batch/kidspersonalitybatch/SaveKidsItemProcessor.java
  src/main/java/com/ureca/idle/batch/kidspersonalitybatch/SaveKidsItemReader.java
  src/main/java/com/ureca/idle/batch/kidspersonalitybatch/SaveKidsItemWriter.java
  src/main/java/com/ureca/idle/batch/kidspersonalitybatch/SaveKidsJobConfiguration.java
  src/main/java/com/ureca/idle/batch/kidspersonalitybatch/SaveKidsStepConfiguration.java
  src/main/java/com/ureca/idle/originapi/persistence/kid/KidRepository.java
  src/main/resources/application.yml
Labels: enhancement

#37 [ID-64] 엔티티 오류 수정
  src/main/java/com/ureca/idle/jpa/kid/Kid.java
Labels: bug
